PKGFLAG   = -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS
EXTHDRS   = v3SvrBase.h  v3SvrBoolector.h  v3SvrHandler.h  v3SvrMiniSat.h  v3SvrSatHelper.h  v3SvrType.h

include ../Makefile.in
include ../Makefile.lib
